version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Bucharest"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Bucharest"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: "deps"
      include: "scope"
